export interface Card {
  id: string
  name: string
  set: string
  cardNumber: string
  imageUrl: string
  grade: string
  price: number
  change: number
  trend: 'up' | 'down'
  score: number
  breakdown: { growth: number; liquidity: number; volatility: number; demand: number }
  verdict: string
  verdictShort: string
  rarity: string
  year: string
  emoji: string
  tags: string[]
  history: { month: string; price: number }[]
  sales: { date: string; price: number; platform: string }[]
  // Analysis data
  marketAvg: number
  priceRange90d: { min: number; max: number }
  volatilityPct: number
  volatilityLabel: string
  liquidityScore: number
  liquidityLabel: string
  liquidityDesc: string
  trendPct: number
  trendLabel: string
  holdScore: number
  holdVerdict: string
  holdDescription: string
  monthlyGrowth: number
  projections: {
    m3: { price: number; pct: number }
    m6: { price: number; pct: number }
    m12: { price: number; pct: number }
  }
  holdFactors: { title: string; description: string }[]
  aiInsights: string[]
  ebayListings: { title: string; date: string; price: number; badge?: 'HIGH' | 'LOW' }[]
}

export const cards: Card[] = [
  {
    id: 'charizard-base-psa9',
    name: 'Charizard',
    set: 'Base Set',
    cardNumber: '4/102',
    imageUrl: 'https://images.pokemontcg.io/base1/4_hires.png',
    grade: 'PSA 9',
    price: 4850,
    change: 12.4,
    trend: 'up',
    score: 87,
    breakdown: { growth: 91, liquidity: 88, volatility: 72, demand: 96 },
    verdict: 'Bullish long-term outlook. Charizard Base Set PSA 9 continues to demonstrate exceptional collector demand with consistent appreciation over 18 months. Low circulating supply relative to demand, combined with strong cultural relevance, suggests continued upward pressure on prices.',
    verdictShort: 'Strong collector demand. Consistent appreciation.',
    rarity: 'Holo Rare', year: '1999', emoji: '🔥',
    tags: ['Holo Rare', 'Pokémon', 'Stage 2', 'Base Set'],
    history: [
      { month: 'May', price: 3200 }, { month: 'Jun', price: 3450 }, { month: 'Jul', price: 3380 },
      { month: 'Aug', price: 3750 }, { month: 'Sep', price: 3900 }, { month: 'Oct', price: 4100 },
      { month: 'Nov', price: 4350 }, { month: 'Dec', price: 4200 }, { month: 'Jan', price: 4480 },
      { month: 'Feb', price: 4600 }, { month: 'Mar', price: 4750 }, { month: 'Apr', price: 4850 },
    ],
    sales: [
      { date: 'Apr 14', price: 4900, platform: 'eBay' }, { date: 'Apr 11', price: 4820, platform: 'eBay' },
      { date: 'Apr 8', price: 4780, platform: 'PWCC' }, { date: 'Apr 3', price: 4850, platform: 'eBay' },
      { date: 'Mar 28', price: 4700, platform: 'eBay' },
    ],
    marketAvg: 5100,
    priceRange90d: { min: 4200, max: 5800 },
    volatilityPct: 23,
    volatilityLabel: 'Moderate',
    liquidityScore: 88,
    liquidityLabel: 'High',
    liquidityDesc: 'High sales activity with consistent collector demand. PSA 9 copies sell within days when priced at or below market value, driven by sustained multi-generational interest in Base Set Charizard.',
    trendPct: 27.4,
    trendLabel: 'Rising',
    holdScore: 87,
    holdVerdict: 'STRONG HOLD',
    holdDescription: 'Base Set Charizard remains the cornerstone of Pokémon card collecting with sustained appreciation across all grades. PSA 9\'s rarity premium and strong floor support makes this an exceptional long-term hold. Cultural relevance shows no signs of decline.',
    monthlyGrowth: 3.2,
    projections: {
      m3: { price: 5560, pct: 15 },
      m6: { price: 6380, pct: 32 },
      m12: { price: 8400, pct: 73 },
    },
    holdFactors: [
      { title: 'Iconic Character Premium', description: 'Charizard remains the most collected Pokémon with multi-generational demand. Base Set provenance and original 1999 English release carry lasting historical significance.' },
      { title: 'PSA 9 Population Scarcity', description: 'Centering and surface defects limit PSA 9 population growth. Limited new supply from existing card stock maintains upward price pressure.' },
      { title: 'Cultural Resilience', description: 'Pokémon franchise continues growing with new generations of fans, expanding the collector base that drives demand for iconic vintage cards.' },
    ],
    aiInsights: [
      'Exact sold prices: $4,780–$4,900 AUD across eBay and PWCC in the last 30 days. Each sale closing above the prior month\'s average.',
      'Price momentum accelerating with pattern consistent with supply shock — fewer PSA 9s returning from grading submissions.',
      'Raw ungraded copies in comparable condition selling at $1,200–$1,800 AUD. PSA 9 represents a 3–4x premium over raw.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Pokemon 1999 Base Set Charizard #4 PSA 9 MINT', date: 'Apr 14, 2026', price: 4900, badge: 'HIGH' },
      { title: 'Charizard Base Set 4/102 Holo Rare PSA 9', date: 'Apr 11, 2026', price: 4820 },
      { title: 'Pokemon Charizard Base Set Holo Rare PSA 9', date: 'Apr 8, 2026', price: 4780 },
      { title: '1999 Pokemon Base Set Charizard Holo PSA 9 MINT', date: 'Apr 3, 2026', price: 4850 },
      { title: 'Charizard Base Set 1999 Holo Rare PSA 9 Mint', date: 'Mar 28, 2026', price: 4700 },
    ],
  },
  {
    id: 'lugia-v-alt-psa10',
    name: 'Lugia V Alt Art',
    set: 'Silver Tempest',
    cardNumber: 'TG30/TG30',
    imageUrl: 'https://images.pokemontcg.io/swsh12/186_hires.png',
    grade: 'PSA 10',
    price: 1740,
    change: -8.2,
    trend: 'down',
    score: 71,
    breakdown: { growth: 58, liquidity: 74, volatility: 45, demand: 82 },
    verdict: 'Short-term correction underway. Lugia V Alt Art PSA 10 experienced post-release price compression typical of modern chase cards. Supply is normalising as more PSA 10s return from grading. The card retains strong collector appeal with floor support likely around $1,500.',
    verdictShort: 'Post-release correction. Floor forming.',
    rarity: 'Alt Art Ultra Rare', year: '2022', emoji: '🌊',
    tags: ['Alt Art Ultra Rare', 'Pokémon V', 'Basic', 'Trainer Gallery'],
    history: [
      { month: 'May', price: 2400 }, { month: 'Jun', price: 2250 }, { month: 'Jul', price: 2100 },
      { month: 'Aug', price: 2050 }, { month: 'Sep', price: 1980 }, { month: 'Oct', price: 1920 },
      { month: 'Nov', price: 2100 }, { month: 'Dec', price: 2200 }, { month: 'Jan', price: 2050 },
      { month: 'Feb', price: 1900 }, { month: 'Mar', price: 1850 }, { month: 'Apr', price: 1740 },
    ],
    sales: [
      { date: 'Apr 15', price: 1760, platform: 'eBay' }, { date: 'Apr 12', price: 1720, platform: 'eBay' },
      { date: 'Apr 9', price: 1780, platform: 'eBay' }, { date: 'Apr 5', price: 1800, platform: 'PWCC' },
      { date: 'Apr 1', price: 1850, platform: 'eBay' },
    ],
    marketAvg: 1950,
    priceRange90d: { min: 1580, max: 2350 },
    volatilityPct: 34,
    volatilityLabel: 'Volatile',
    liquidityScore: 74,
    liquidityLabel: 'Moderate',
    liquidityDesc: 'Moderate sales activity with demand influenced by market sentiment. PSA 10 copies require competitive pricing to sell within 2 weeks. Activity is trending lower as correction continues.',
    trendPct: -27.5,
    trendLabel: 'Falling',
    holdScore: 71,
    holdVerdict: 'HOLD',
    holdDescription: 'Post-release correction is compressing prices as PSA 10 grading returns normalize supply. Floor around $1,500 AUD is supported by strong collector appeal. Monitor for volume stabilization before adding more.',
    monthlyGrowth: -2.1,
    projections: {
      m3: { price: 1630, pct: -6 },
      m6: { price: 1520, pct: -13 },
      m12: { price: 1800, pct: 3 },
    },
    holdFactors: [
      { title: 'Post-Release Supply Pressure', description: 'Ongoing PSA returns from Silver Tempest submissions increasing PSA 10 population, suppressing short-term price. 3,400+ PSA 10 copies graded to date.' },
      { title: 'Strong Collector Floor', description: 'Lugia\'s nostalgic appeal creates consistent floor support. Alt Art treatment with premium artwork maintains long-term demand despite short-term correction.' },
      { title: 'Modern Set Population Risk', description: 'Modern sets face print run uncertainty. Population reports will be critical over next 6 months for establishing accurate price trajectory.' },
    ],
    aiInsights: [
      'Exact sold prices: $1,720–$1,800 AUD in last 30 days. Prices declining approximately $50–80 per week.',
      'PSA population data shows 3,400+ PSA 10 copies graded with more expected from ongoing submissions creating continued supply pressure.',
      'CAUTION: Downward trend is technical correction, not fundamental breakdown. $1,500 AUD floor has historically held across three separate tests.',
      'Data quality: Good. 5 sold listings in 30-day window. Sufficient for short-term analysis but limited for long-term projections.',
    ],
    ebayListings: [
      { title: 'Pokemon Silver Tempest Lugia V Alt Art TG30 PSA 10 GEM MINT', date: 'Apr 15, 2026', price: 1760, badge: 'HIGH' },
      { title: 'Lugia V Alt Art TG30/TG30 PSA 10', date: 'Apr 12, 2026', price: 1720 },
      { title: 'Silver Tempest Lugia V Trainer Gallery Alt Art PSA 10', date: 'Apr 9, 2026', price: 1780 },
      { title: 'Pokemon Lugia V TG30 Alt Art PSA 10 Gem Mint', date: 'Apr 5, 2026', price: 1800 },
      { title: 'Lugia V Alt Art PSA 10 Silver Tempest TG30/TG30', date: 'Apr 1, 2026', price: 1850 },
    ],
  },
  {
    id: 'eevee-promo-psa10',
    name: 'Eevee',
    set: 'Black Star Promo',
    cardNumber: 'SM229',
    imageUrl: 'https://images.pokemontcg.io/smp/SM184_hires.png',
    grade: 'PSA 10',
    price: 680,
    change: 24.8,
    trend: 'up',
    score: 79,
    breakdown: { growth: 88, liquidity: 62, volatility: 68, demand: 85 },
    verdict: 'Emerging breakout candidate. Eevee Black Star Promo PSA 10 is benefiting from growing nostalgia demand and limited PSA 10 population. Strong social media presence is driving new collector interest. Recommend monitoring for sustained volume confirmation.',
    verdictShort: 'Breakout momentum. Low supply driving gains.',
    rarity: 'Promo', year: '1999', emoji: '⭐',
    tags: ['Black Star Promo', 'Pokémon', 'Basic', '1999 Vintage'],
    history: [
      { month: 'May', price: 420 }, { month: 'Jun', price: 430 }, { month: 'Jul', price: 455 },
      { month: 'Aug', price: 440 }, { month: 'Sep', price: 470 }, { month: 'Oct', price: 490 },
      { month: 'Nov', price: 520 }, { month: 'Dec', price: 545 }, { month: 'Jan', price: 580 },
      { month: 'Feb', price: 610 }, { month: 'Mar', price: 650 }, { month: 'Apr', price: 680 },
    ],
    sales: [
      { date: 'Apr 13', price: 695, platform: 'eBay' }, { date: 'Apr 10', price: 670, platform: 'eBay' },
      { date: 'Apr 6', price: 680, platform: 'eBay' }, { date: 'Mar 30', price: 645, platform: 'PWCC' },
      { date: 'Mar 25', price: 640, platform: 'eBay' },
    ],
    marketAvg: 720,
    priceRange90d: { min: 580, max: 810 },
    volatilityPct: 28,
    volatilityLabel: 'Moderate',
    liquidityScore: 62,
    liquidityLabel: 'Moderate',
    liquidityDesc: 'Moderate sales activity with growing demand from nostalgia-driven collectors. PSA 10 copies are scarce and typically sell within 1–2 weeks at market pricing. Volume increasing with momentum.',
    trendPct: 47.8,
    trendLabel: 'Rising',
    holdScore: 79,
    holdVerdict: 'STRONG HOLD',
    holdDescription: 'Emerging breakout fueled by nostalgia demand and extremely limited PSA 10 supply. Fewer than 200 PSA 10 copies exist. Social media exposure continuing to drive new collector discovery.',
    monthlyGrowth: 5.1,
    projections: {
      m3: { price: 784, pct: 15 },
      m6: { price: 893, pct: 31 },
      m12: { price: 1105, pct: 63 },
    },
    holdFactors: [
      { title: 'Extreme PSA 10 Scarcity', description: 'Fewer than 200 PSA 10 copies in population report. Eevee promo cards are notoriously difficult to grade gem due to centering issues on original print run.' },
      { title: 'Nostalgia Breakout Momentum', description: 'Social media collector platforms driving new demand from 25–35 year olds rediscovering childhood Pokémon. Eevee\'s broad appeal across generations amplifies this effect.' },
      { title: '1999 Vintage Premium', description: 'Black Star Promo cards from 1999 carry increasing vintage premium. Early Pokémon merchandise is gaining recognition as historically significant collectibles.' },
    ],
    aiInsights: [
      'Exact sold prices: $640–$695 AUD in last 30 days. Accelerating appreciation of approximately $15 per week.',
      'Population report: 189 PSA 10 copies confirmed as of last check. Grade 10 submission rate approximately 8% — extremely low.',
      'Breakout confirmed: Three consecutive months of new price highs. Pattern consistent with supply-constrained appreciation cycle.',
      'Data quality: Moderate. 5 sold listings in 30 days. Limited data creates uncertainty but confirms upward direction.',
    ],
    ebayListings: [
      { title: 'Pokemon SM229 Eevee Black Star Promo PSA 10 GEM MINT', date: 'Apr 13, 2026', price: 695, badge: 'HIGH' },
      { title: 'Eevee SM229 Black Star Promo PSA 10 Gem Mint', date: 'Apr 10, 2026', price: 670 },
      { title: 'Pokemon Black Star Promo Eevee PSA 10 GEM MINT', date: 'Apr 6, 2026', price: 680 },
      { title: 'Eevee Promo SM229 PSA 10 Pokemon', date: 'Mar 30, 2026', price: 645 },
      { title: '1999 Pokemon Eevee Black Star Promo PSA 10 Vintage', date: 'Mar 25, 2026', price: 640 },
    ],
  },
  {
    id: 'umbreon-vmax-alt-psa10',
    name: 'Umbreon VMAX Alt Art',
    set: 'Evolving Skies',
    cardNumber: '215/203',
    imageUrl: 'https://images.pokemontcg.io/swsh7/215_hires.png',
    grade: 'PSA 10',
    price: 2850,
    change: 5.1,
    trend: 'up',
    score: 95,
    breakdown: { growth: 94, liquidity: 82, volatility: 88, demand: 99 },
    verdict: 'Blue-chip modern. Umbreon VMAX Alt Art PSA 10 is one of the most sought-after modern Pokémon cards globally. The stunning artwork, low PSA 10 population relative to demand, and Umbreon\'s enduring popularity create a compelling long-term hold case.',
    verdictShort: 'Blue-chip modern. Exceptional artwork demand.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Evolving Skies', 'Secret Rare'],
    history: [
      { month: 'May', price: 1900 }, { month: 'Jun', price: 2050 }, { month: 'Jul', price: 2200 },
      { month: 'Aug', price: 2150 }, { month: 'Sep', price: 2300 }, { month: 'Oct', price: 2450 },
      { month: 'Nov', price: 2380 }, { month: 'Dec', price: 2500 }, { month: 'Jan', price: 2600 },
      { month: 'Feb', price: 2700 }, { month: 'Mar', price: 2780 }, { month: 'Apr', price: 2850 },
    ],
    sales: [
      { date: 'Apr 14', price: 2900, platform: 'eBay' }, { date: 'Apr 10', price: 2840, platform: 'eBay' },
      { date: 'Apr 5', price: 2870, platform: 'PWCC' }, { date: 'Mar 28', price: 2800, platform: 'eBay' },
      { date: 'Mar 20', price: 2750, platform: 'eBay' },
    ],
    marketAvg: 3100,
    priceRange90d: { min: 2400, max: 3600 },
    volatilityPct: 18,
    volatilityLabel: 'Stable',
    liquidityScore: 82,
    liquidityLabel: 'High',
    liquidityDesc: 'High demand with consistent sales activity. Umbreon VMAX Alt Art PSA 10 sells within days when competitively priced. Strong global collector base with consistent buyer depth across eBay and auction platforms.',
    trendPct: 20.3,
    trendLabel: 'Rising',
    holdScore: 95,
    holdVerdict: 'STRONG HOLD',
    holdDescription: 'Umbreon VMAX Alt Art is the definitive blue-chip modern Pokémon card. Exceptional artwork, strong character appeal, and a growing PSA 10 premium make this a cornerstone portfolio card. Long-term appreciation outlook remains very positive.',
    monthlyGrowth: 2.8,
    projections: {
      m3: { price: 3240, pct: 14 },
      m6: { price: 3720, pct: 31 },
      m12: { price: 4480, pct: 57 },
    },
    holdFactors: [
      { title: 'Iconic Artwork Premium', description: 'The Umbreon VMAX Alt Art features one of the most celebrated artworks in modern Pokémon TCG. This creates sustained collector demand beyond competitive play.' },
      { title: 'PSA 10 Scarcity', description: 'Difficult centering and surface quality requirements limit PSA 10 population. Grade 10 copies command a growing premium over PSA 9 as population grows slowly.' },
      { title: 'Character Popularity', description: 'Umbreon is consistently ranked among the most popular Pokémon globally, driving demand that transcends competitive viability.' },
    ],
    aiInsights: [
      'Exact sold prices: $2,800–$2,900 AUD in last 30 days. Steady appreciation of approximately $50 per week.',
      'PSA population: 4,200+ PSA 10 copies graded but demand consistently outpacing new supply entering the market.',
      'Alt Art cards from Evolving Skies have shown consistent long-term appreciation. Espeon VMAX Alt Art trading at similar premium.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Umbreon VMAX Alt Art 215/203 Evolving Skies PSA 10 GEM MINT', date: 'Apr 14, 2026', price: 2900, badge: 'HIGH' },
      { title: 'Pokemon Umbreon VMAX Alt Art PSA 10 Evolving Skies', date: 'Apr 10, 2026', price: 2840 },
      { title: 'Umbreon VMAX 215/203 Alt Art PSA 10 — Pack Fresh', date: 'Apr 5, 2026', price: 2870 },
      { title: 'Evolving Skies Umbreon VMAX Alt Art PSA 10 Gem Mint', date: 'Mar 28, 2026', price: 2800 },
      { title: 'Umbreon VMAX Alt Art PSA 10 Evolving Skies 215/203', date: 'Mar 20, 2026', price: 2750 },
    ],
  },
  {
    id: 'rayquaza-vmax-alt-psa10',
    name: 'Rayquaza VMAX Alt Art',
    set: 'Evolving Skies',
    cardNumber: '218/203',
    imageUrl: 'https://images.pokemontcg.io/swsh7/218_hires.png',
    grade: 'PSA 10',
    price: 420,
    change: 6.4,
    trend: 'up',
    score: 83,
    breakdown: { growth: 85, liquidity: 80, volatility: 68, demand: 88 },
    verdict: 'Sustained appreciation driven by iconic artwork and Dragon-type prestige. Rayquaza VMAX Alt Art continues to benefit from strong collector demand and consistent secondary market activity.',
    verdictShort: 'Strong growth. Dragon-type premium.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '🐉',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Evolving Skies'],
    history: [
      { month: 'May', price: 290 }, { month: 'Jun', price: 305 }, { month: 'Jul', price: 315 },
      { month: 'Aug', price: 330 }, { month: 'Sep', price: 340 }, { month: 'Oct', price: 355 },
      { month: 'Nov', price: 365 }, { month: 'Dec', price: 375 }, { month: 'Jan', price: 385 },
      { month: 'Feb', price: 395 }, { month: 'Mar', price: 408 }, { month: 'Apr', price: 420 },
    ],
    sales: [
      { date: 'Apr 15', price: 425, platform: 'eBay' }, { date: 'Apr 11', price: 418, platform: 'eBay' },
      { date: 'Apr 6', price: 412, platform: 'eBay' }, { date: 'Apr 1', price: 420, platform: 'PWCC' },
      { date: 'Mar 25', price: 405, platform: 'eBay' },
    ],
    marketAvg: 440,
    priceRange90d: { min: 370, max: 510 },
    volatilityPct: 18,
    volatilityLabel: 'Low-Moderate',
    liquidityScore: 80,
    liquidityLabel: 'High',
    liquidityDesc: 'Strong sales velocity with consistent buyer interest. Rayquaza VMAX Alt Art from Evolving Skies maintains high liquidity thanks to broad collector appeal and Dragon-type prestige.',
    trendPct: 18.3,
    trendLabel: 'Rising',
    holdScore: 83,
    holdVerdict: 'STRONG HOLD',
    holdDescription: 'Evolving Skies Alt Arts have proven to be among the strongest appreciating modern cards. Rayquaza\'s iconic status and the set\'s Dragon-type focus create a unique collector premium with a well-supported floor.',
    monthlyGrowth: 2.8,
    projections: {
      m3: { price: 478, pct: 14 },
      m6: { price: 546, pct: 30 },
      m12: { price: 672, pct: 60 },
    },
    holdFactors: [
      { title: 'Dragon-Type Collector Premium', description: 'Dragon-type Pokémon command a premium in the secondary market due to rarity and prestige. Rayquaza is the most iconic Dragon-type with strong cross-generational recognition.' },
      { title: 'Evolving Skies Set Strength', description: 'Evolving Skies is widely regarded as one of the strongest modern sets. Multiple Alt Arts from the set continue to appreciate, lifting the entire set\'s profile.' },
      { title: 'Competitive & Collector Overlap', description: 'Rayquaza VMAX maintains relevance in both competitive play and collecting, broadening the demand base and supporting price stability.' },
    ],
    aiInsights: [
      'Exact sold prices: $412–$425 AUD in the last 30 days. Steady month-over-month appreciation of ~$12.',
      'Evolving Skies Alt Arts as a group are up an average of 19% YTD, with Rayquaza among the top performers.',
      'PSA 10 population growing slowly due to centering sensitivity. New submissions returning with ~35% PSA 10 rate.',
      'Data quality: Strong. 5 sold listings in 30-day window.',
    ],
    ebayListings: [
      { title: 'Rayquaza VMAX Alt Art 218/203 Evolving Skies PSA 10 GEM MINT', date: 'Apr 15, 2026', price: 425, badge: 'HIGH' },
      { title: 'Pokemon Rayquaza VMAX Alt Art PSA 10 Evolving Skies', date: 'Apr 11, 2026', price: 418 },
      { title: 'Rayquaza VMAX 218/203 Alt Art PSA 10 — Gem Mint', date: 'Apr 6, 2026', price: 412, badge: 'LOW' },
      { title: 'Evolving Skies Rayquaza VMAX Alt Art PSA 10', date: 'Apr 1, 2026', price: 420 },
      { title: 'Rayquaza VMAX Alt Art PSA 10 Evolving Skies 218/203', date: 'Mar 25, 2026', price: 405 },
    ],
  },
  {
    id: 'mew-vmax-alt-psa10',
    name: 'Mew VMAX Alt Art',
    set: 'Fusion Strike',
    cardNumber: '269/264',
    imageUrl: 'https://images.pokemontcg.io/swsh8/269_hires.png',
    grade: 'PSA 10',
    price: 320,
    change: 4.8,
    trend: 'up',
    score: 77,
    breakdown: { growth: 76, liquidity: 78, volatility: 62, demand: 84 },
    verdict: 'Solid mid-tier modern card with steady appreciation. Mew VMAX Alt Art benefits from Mew\'s legendary status and the appeal of Fusion Strike\'s chase cards. Consistent demand with moderate growth trajectory.',
    verdictShort: 'Steady growth. Legendary appeal.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '🌸',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Fusion Strike'],
    history: [
      { month: 'May', price: 230 }, { month: 'Jun', price: 245 }, { month: 'Jul', price: 252 },
      { month: 'Aug', price: 260 }, { month: 'Sep', price: 268 }, { month: 'Oct', price: 278 },
      { month: 'Nov', price: 285 }, { month: 'Dec', price: 292 }, { month: 'Jan', price: 300 },
      { month: 'Feb', price: 308 }, { month: 'Mar', price: 315 }, { month: 'Apr', price: 320 },
    ],
    sales: [
      { date: 'Apr 14', price: 325, platform: 'eBay' }, { date: 'Apr 9', price: 318, platform: 'eBay' },
      { date: 'Apr 4', price: 315, platform: 'eBay' }, { date: 'Mar 30', price: 320, platform: 'PWCC' },
      { date: 'Mar 24', price: 310, platform: 'eBay' },
    ],
    marketAvg: 340,
    priceRange90d: { min: 285, max: 390 },
    volatilityPct: 16,
    volatilityLabel: 'Low',
    liquidityScore: 78,
    liquidityLabel: 'Good',
    liquidityDesc: 'Reliable sales cadence with Mew\'s legendary status driving consistent buyer interest. PSA 10 copies from Fusion Strike sell steadily, supported by both competitive players and collectors.',
    trendPct: 13.2,
    trendLabel: 'Rising',
    holdScore: 77,
    holdVerdict: 'HOLD',
    holdDescription: 'Mew VMAX Alt Art offers a solid hold proposition with low volatility and steady appreciation. While growth rates trail top-tier Alt Arts, the legendary Pokémon premium and consistent demand provide a reliable floor.',
    monthlyGrowth: 2.1,
    projections: {
      m3: { price: 360, pct: 13 },
      m6: { price: 405, pct: 27 },
      m12: { price: 480, pct: 50 },
    },
    holdFactors: [
      { title: 'Legendary Pokémon Premium', description: 'Mew holds a unique place in Pokémon lore as the original Legendary. This drives collector interest that persists regardless of competitive meta shifts.' },
      { title: 'Low Population Growth', description: 'Fusion Strike PSA 10s continue to return at a moderate rate. Centering requirements keep population growth measured, supporting existing holder positions.' },
      { title: '→ Moderate Growth Ceiling', description: 'Without a major competitive or cultural catalyst, Mew VMAX Alt Art is expected to appreciate steadily rather than spike. Best viewed as a stable mid-term hold.' },
    ],
    aiInsights: [
      'Exact sold prices: $315–$325 AUD in the last 30 days. Consistent weekly appreciation of ~$5–8.',
      'Fusion Strike as a set has shown steady appreciation with multiple Alt Arts trending upward simultaneously.',
      'Mew VMAX Alt Art PSA 9 selling at ~$180 AUD, making the PSA 10 premium approximately 78%.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Mew VMAX Alt Art 269/264 Fusion Strike PSA 10 GEM MINT', date: 'Apr 14, 2026', price: 325, badge: 'HIGH' },
      { title: 'Pokemon Mew VMAX Alt Art PSA 10 Fusion Strike', date: 'Apr 9, 2026', price: 318 },
      { title: 'Mew VMAX 269/264 Alt Art PSA 10 — Pack Fresh Gem Mint', date: 'Apr 4, 2026', price: 315 },
      { title: 'Fusion Strike Mew VMAX Alt Art PSA 10 Gem Mint', date: 'Mar 30, 2026', price: 320 },
      { title: 'Mew VMAX Alt Art PSA 10 Fusion Strike 269/264', date: 'Mar 24, 2026', price: 310, badge: 'LOW' },
    ],
  },
  {
    id: 'blastoise-base-psa9',
    name: 'Blastoise',
    set: 'Base Set',
    cardNumber: '2/102',
    imageUrl: 'https://images.pokemontcg.io/base1/2_hires.png',
    grade: 'PSA 9',
    price: 1450,
    change: 2.1,
    trend: 'up',
    score: 74,
    breakdown: { growth: 72, liquidity: 76, volatility: 68, demand: 80 },
    verdict: 'Solid vintage hold. Blastoise Base Set PSA 9 benefits from its status as one of the original three starter Pokémon and its place in the iconic 1999 Base Set. Steady appreciation with moderate volatility makes it a reliable long-term collector piece.',
    verdictShort: 'Solid vintage hold. Starter Pokémon premium.',
    rarity: 'Holo Rare', year: '1999', emoji: '',
    tags: ['Holo Rare', 'Pokémon', 'Stage 2', 'Base Set'],
    history: [
      { month: 'May', price: 1100 }, { month: 'Jun', price: 1140 }, { month: 'Jul', price: 1120 },
      { month: 'Aug', price: 1180 }, { month: 'Sep', price: 1220 }, { month: 'Oct', price: 1260 },
      { month: 'Nov', price: 1300 }, { month: 'Dec', price: 1280 }, { month: 'Jan', price: 1340 },
      { month: 'Feb', price: 1380 }, { month: 'Mar', price: 1420 }, { month: 'Apr', price: 1450 },
    ],
    sales: [
      { date: 'Apr 13', price: 1480, platform: 'eBay' }, { date: 'Apr 9', price: 1440, platform: 'eBay' },
      { date: 'Apr 4', price: 1460, platform: 'PWCC' }, { date: 'Mar 29', price: 1420, platform: 'eBay' },
      { date: 'Mar 22', price: 1400, platform: 'eBay' },
    ],
    marketAvg: 1580,
    priceRange90d: { min: 1280, max: 1750 },
    volatilityPct: 19,
    volatilityLabel: 'Moderate',
    liquidityScore: 76,
    liquidityLabel: 'Good',
    liquidityDesc: 'Consistent sales activity driven by vintage collector demand. Blastoise PSA 9 sells steadily on eBay and auction platforms, though turnover is slower than Charizard. Buyer depth is solid at market price.',
    trendPct: 11.5,
    trendLabel: 'Rising',
    holdScore: 74,
    holdVerdict: 'HOLD',
    holdDescription: 'Blastoise Base Set remains a cornerstone vintage Pokémon card. Its status as a starter Pokémon and its inclusion in the original 1999 Base Set ensures enduring collector interest. Steady growth with moderate upside.',
    monthlyGrowth: 1.8,
    projections: {
      m3: { price: 1628, pct: 12 },
      m6: { price: 1798, pct: 24 },
      m12: { price: 2030, pct: 40 },
    },
    holdFactors: [
      { title: 'Original Starter Premium', description: 'Blastoise is one of the original three starter Pokémon from Generation I. This drives persistent collector demand that mirrors Charizard, albeit at a lower magnitude.' },
      { title: 'Base Set Historical Significance', description: 'Cards from the 1999 Base Set carry the greatest historical weight in the hobby. Condition-sensitive PSA 9 copies represent peak value for most vintage collectors.' },
      { title: 'Steady Appreciation Trend', description: 'Price trajectory shows consistent 12-month appreciation without the volatility spikes seen in higher-profile cards, making it a reliable portfolio inclusion.' },
    ],
    aiInsights: [
      'Exact sold prices: $1,400–$1,480 AUD in the last 30 days. Incremental weekly gains averaging $10–15.',
      'Base Set Holo Rares continue to appreciate as a group. Charizard\'s rising tide lifts all starter Pokémon valuations.',
      'PSA 9 population remains relatively stable. Grade inflation from raw submissions is moderate.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Pokemon 1999 Base Set Blastoise #2 PSA 9 MINT', date: 'Apr 13, 2026', price: 1480, badge: 'HIGH' },
      { title: 'Blastoise Base Set 2/102 Holo Rare PSA 9', date: 'Apr 9, 2026', price: 1440 },
      { title: 'Pokemon Blastoise Base Set Holo Rare PSA 9', date: 'Apr 4, 2026', price: 1460 },
      { title: '1999 Pokemon Base Set Blastoise Holo PSA 9 MINT', date: 'Mar 29, 2026', price: 1420 },
      { title: 'Blastoise Base Set 1999 Holo Rare PSA 9 Mint', date: 'Mar 22, 2026', price: 1400, badge: 'LOW' },
    ],
  },
  {
    id: 'espeon-vmax-alt-psa10',
    name: 'Espeon VMAX Alt Art',
    set: 'Evolving Skies',
    cardNumber: '208/203',
    imageUrl: 'https://images.pokemontcg.io/swsh7/208_hires.png',
    grade: 'PSA 10',
    price: 320,
    change: 1.4,
    trend: 'down',
    score: 79,
    breakdown: { growth: 75, liquidity: 80, volatility: 71, demand: 88 },
    verdict: 'Stable modern hold. Espeon VMAX Alt Art PSA 10 benefits from the same Evolving Skies prestige as Umbreon VMAX, though at a lower price point. Recent minor dip represents a potential accumulation opportunity given the card\'s strong demand fundamentals.',
    verdictShort: 'Stable modern. Evolving Skies prestige.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Evolving Skies', 'Secret Rare'],
    history: [
      { month: 'May', price: 240 }, { month: 'Jun', price: 255 }, { month: 'Jul', price: 265 },
      { month: 'Aug', price: 258 }, { month: 'Sep', price: 272 }, { month: 'Oct', price: 285 },
      { month: 'Nov', price: 292 }, { month: 'Dec', price: 300 }, { month: 'Jan', price: 308 },
      { month: 'Feb', price: 318 }, { month: 'Mar', price: 325 }, { month: 'Apr', price: 320 },
    ],
    sales: [
      { date: 'Apr 12', price: 318, platform: 'eBay' }, { date: 'Apr 8', price: 322, platform: 'eBay' },
      { date: 'Apr 3', price: 325, platform: 'PWCC' }, { date: 'Mar 27', price: 315, platform: 'eBay' },
      { date: 'Mar 19', price: 310, platform: 'eBay' },
    ],
    marketAvg: 345,
    priceRange90d: { min: 290, max: 380 },
    volatilityPct: 14,
    volatilityLabel: 'Stable',
    liquidityScore: 80,
    liquidityLabel: 'High',
    liquidityDesc: 'Strong sales activity supported by Evolving Skies collector demand. Espeon VMAX Alt Art PSA 10 sells reliably with minimal time on market when priced competitively. Consistent buyer pool across global eBay markets.',
    trendPct: 14.2,
    trendLabel: 'Steady',
    holdScore: 79,
    holdVerdict: 'HOLD',
    holdDescription: 'Espeon VMAX Alt Art is a high-quality modern hold bolstered by the Evolving Skies set premium and Espeon\'s strong fanbase. The slight recent dip does not signal a structural change — fundamentals remain solid.',
    monthlyGrowth: 1.5,
    projections: {
      m3: { price: 362, pct: 13 },
      m6: { price: 400, pct: 25 },
      m12: { price: 470, pct: 47 },
    },
    holdFactors: [
      { title: 'Evolving Skies Set Prestige', description: 'Evolving Skies is one of the most celebrated modern sets. Alt Arts from this set consistently trade at a premium over equivalent cards from other releases.' },
      { title: 'Espeon Fan Demand', description: 'Espeon is a consistently popular Eeveelution. High fan recognition drives collector demand that remains stable regardless of competitive play shifts.' },
      { title: 'Dip Accumulation Opportunity', description: 'The minor recent price dip appears driven by short-term supply rather than weakened demand. Historical pattern shows recoveries within 4–6 weeks.' },
    ],
    aiInsights: [
      'Exact sold prices: $310–$325 AUD in the last 30 days. Slight softening consistent with broader market consolidation.',
      'Espeon VMAX Alt Art trades at a discount to Umbreon VMAX Alt Art despite comparable artwork quality — potential upside if gap narrows.',
      'Evolving Skies Alt Arts as a group continue to appreciate. Glaceon and Leafeon VMAX Alt Arts also trending positively.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Espeon VMAX Alt Art 208/203 Evolving Skies PSA 10 GEM MINT', date: 'Apr 12, 2026', price: 318 },
      { title: 'Pokemon Espeon VMAX Alt Art PSA 10 Evolving Skies', date: 'Apr 8, 2026', price: 322, badge: 'HIGH' },
      { title: 'Espeon VMAX 208/203 Alt Art PSA 10 — Pack Fresh', date: 'Apr 3, 2026', price: 325 },
      { title: 'Evolving Skies Espeon VMAX Alt Art PSA 10 Gem Mint', date: 'Mar 27, 2026', price: 315 },
      { title: 'Espeon VMAX Alt Art PSA 10 Evolving Skies 208/203', date: 'Mar 19, 2026', price: 310, badge: 'LOW' },
    ],
  },
  {
    id: 'sylveon-vmax-alt-psa10',
    name: 'Sylveon VMAX Alt Art',
    set: 'Evolving Skies',
    cardNumber: '212/203',
    imageUrl: 'https://images.pokemontcg.io/swsh7/212_hires.png',
    grade: 'PSA 10',
    price: 275,
    change: 4.7,
    trend: 'up',
    score: 76,
    breakdown: { growth: 78, liquidity: 72, volatility: 70, demand: 82 },
    verdict: 'Steady growth trajectory. Sylveon VMAX Alt Art PSA 10 has shown consistent appreciation as the Eeveelution fan collector base expands. Below the price ceiling of Umbreon and Espeon, it represents a lower-entry Alt Art with solid upside.',
    verdictShort: 'Steady growth. Lower-entry Alt Art with upside.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Evolving Skies', 'Secret Rare'],
    history: [
      { month: 'May', price: 185 }, { month: 'Jun', price: 195 }, { month: 'Jul', price: 202 },
      { month: 'Aug', price: 198 }, { month: 'Sep', price: 210 }, { month: 'Oct', price: 220 },
      { month: 'Nov', price: 232 }, { month: 'Dec', price: 240 }, { month: 'Jan', price: 250 },
      { month: 'Feb', price: 260 }, { month: 'Mar', price: 265 }, { month: 'Apr', price: 275 },
    ],
    sales: [
      { date: 'Apr 14', price: 278, platform: 'eBay' }, { date: 'Apr 9', price: 272, platform: 'eBay' },
      { date: 'Apr 2', price: 270, platform: 'eBay' }, { date: 'Mar 26', price: 265, platform: 'eBay' },
      { date: 'Mar 18', price: 258, platform: 'eBay' },
    ],
    marketAvg: 295,
    priceRange90d: { min: 240, max: 320 },
    volatilityPct: 12,
    volatilityLabel: 'Stable',
    liquidityScore: 72,
    liquidityLabel: 'Good',
    liquidityDesc: 'Moderate-to-strong sales frequency driven by Eeveelution collectors. Sylveon VMAX Alt Art PSA 10 sells reliably within a week at market price. Growing international buyer interest supports consistent demand.',
    trendPct: 12.6,
    trendLabel: 'Rising',
    holdScore: 76,
    holdVerdict: 'HOLD',
    holdDescription: 'Sylveon VMAX Alt Art offers a compelling mid-tier hold within the Evolving Skies Alt Art tier list. The Eeveelution collector premium and continued appreciation trend make this a confident hold with room to grow toward Espeon price levels.',
    monthlyGrowth: 2.2,
    projections: {
      m3: { price: 308, pct: 12 },
      m6: { price: 345, pct: 25 },
      m12: { price: 415, pct: 51 },
    },
    holdFactors: [
      { title: 'Eeveelution Collector Base', description: 'Sylveon benefits from a dedicated Eeveelution fan collector segment that systematically acquires all Eeveelution cards regardless of individual price points.' },
      { title: 'Price Gap Opportunity', description: 'Trading at a discount to Espeon and Umbreon VMAX Alt Arts, Sylveon represents a lower entry price for comparable artwork quality and set prestige.' },
      { title: 'Consistent Monthly Gains', description: 'Price has increased every month for the past 6 months. Low volatility and stable demand suggest this trend is likely to continue.' },
    ],
    aiInsights: [
      'Exact sold prices: $258–$278 AUD in the last 30 days. Consistent weekly appreciation of ~$5.',
      'Eeveelution sets are increasingly collected as complete groups. Sylveon VMAX Alt Art benefits from spillover demand as collectors complete their sets.',
      'PSA 10 population growing modestly. Cards from Evolving Skies are notoriously difficult to grade due to centering issues.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Sylveon VMAX Alt Art 212/203 Evolving Skies PSA 10 GEM MINT', date: 'Apr 14, 2026', price: 278, badge: 'HIGH' },
      { title: 'Pokemon Sylveon VMAX Alt Art PSA 10 Evolving Skies', date: 'Apr 9, 2026', price: 272 },
      { title: 'Sylveon VMAX 212/203 Alt Art PSA 10 — Pack Fresh', date: 'Apr 2, 2026', price: 270 },
      { title: 'Evolving Skies Sylveon VMAX Alt Art PSA 10 Gem Mint', date: 'Mar 26, 2026', price: 265 },
      { title: 'Sylveon VMAX Alt Art PSA 10 Evolving Skies 212/203', date: 'Mar 18, 2026', price: 258, badge: 'LOW' },
    ],
  },
  {
    id: 'gengar-vmax-alt-psa10',
    name: 'Gengar VMAX Alt Art',
    set: 'Fusion Strike',
    cardNumber: '271/264',
    imageUrl: 'https://images.pokemontcg.io/swsh8/271_hires.png',
    grade: 'PSA 10',
    price: 260,
    change: 3.1,
    trend: 'up',
    score: 72,
    breakdown: { growth: 70, liquidity: 68, volatility: 66, demand: 84 },
    verdict: 'Fan-favourite hold with moderate upside. Gengar VMAX Alt Art PSA 10 benefits from Gengar\'s iconic status as one of the most popular Ghost-type Pokémon. Steady demand from the dedicated Gengar collector community provides a reliable price floor.',
    verdictShort: 'Fan-favourite. Reliable Gengar collector demand.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Fusion Strike', 'Secret Rare'],
    history: [
      { month: 'May', price: 185 }, { month: 'Jun', price: 190 }, { month: 'Jul', price: 196 },
      { month: 'Aug', price: 202 }, { month: 'Sep', price: 210 }, { month: 'Oct', price: 218 },
      { month: 'Nov', price: 228 }, { month: 'Dec', price: 235 }, { month: 'Jan', price: 242 },
      { month: 'Feb', price: 250 }, { month: 'Mar', price: 255 }, { month: 'Apr', price: 260 },
    ],
    sales: [
      { date: 'Apr 13', price: 265, platform: 'eBay' }, { date: 'Apr 7', price: 258, platform: 'eBay' },
      { date: 'Apr 1', price: 262, platform: 'eBay' }, { date: 'Mar 25', price: 255, platform: 'eBay' },
      { date: 'Mar 17', price: 248, platform: 'eBay' },
    ],
    marketAvg: 282,
    priceRange90d: { min: 228, max: 305 },
    volatilityPct: 16,
    volatilityLabel: 'Stable',
    liquidityScore: 68,
    liquidityLabel: 'Moderate',
    liquidityDesc: 'Reliable sales activity underpinned by a strong Gengar fan collector base. Fusion Strike as a set has multiple sought-after Alt Arts, which drives continued attention to the set and supports Gengar VMAX price levels.',
    trendPct: 10.4,
    trendLabel: 'Rising',
    holdScore: 72,
    holdVerdict: 'HOLD',
    holdDescription: 'Gengar VMAX Alt Art is a dependable mid-range hold. Gengar\'s enduring popularity across the Pokémon franchise combined with a growing PSA 10 scarcity premium supports continued appreciation. Not a high-growth card but a reliable collector asset.',
    monthlyGrowth: 1.9,
    projections: {
      m3: { price: 289, pct: 11 },
      m6: { price: 320, pct: 23 },
      m12: { price: 375, pct: 44 },
    },
    holdFactors: [
      { title: 'Gengar Icon Status', description: 'Gengar is one of the most recognisable Ghost-type Pokémon and has a dedicated collector following that drives consistent demand for high-grade copies.' },
      { title: 'Fusion Strike Set Momentum', description: 'Fusion Strike features multiple high-demand Alt Arts. Set-level interest benefits all cards including Gengar VMAX, as collectors seek complete Alt Art sets.' },
      { title: 'Moderate Volatility Profile', description: 'Low price volatility indicates a stable collector-driven market rather than speculative trading, supporting a reliable hold position.' },
    ],
    aiInsights: [
      'Exact sold prices: $248–$265 AUD in the last 30 days. Gradual weekly appreciation continuing a 6-month upward trend.',
      'Gengar VMAX Alt Art is frequently bundled with Mew VMAX Alt Art in sales. Combined demand supports individual pricing.',
      'Ghost-type collector base is among the most active in the Pokémon TCG hobby. Gengar consistently outperforms other Ghost-type cards.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Gengar VMAX Alt Art 271/264 Fusion Strike PSA 10 GEM MINT', date: 'Apr 13, 2026', price: 265, badge: 'HIGH' },
      { title: 'Pokemon Gengar VMAX Alt Art PSA 10 Fusion Strike', date: 'Apr 7, 2026', price: 258 },
      { title: 'Gengar VMAX 271/264 Alt Art PSA 10 — Pack Fresh Gem Mint', date: 'Apr 1, 2026', price: 262 },
      { title: 'Fusion Strike Gengar VMAX Alt Art PSA 10 Gem Mint', date: 'Mar 25, 2026', price: 255 },
      { title: 'Gengar VMAX Alt Art PSA 10 Fusion Strike 271/264', date: 'Mar 17, 2026', price: 248, badge: 'LOW' },
    ],
  },
  {
    id: 'leafeon-vmax-alt-psa9',
    name: 'Leafeon VMAX Alt Art',
    set: 'Evolving Skies',
    cardNumber: '211/203',
    imageUrl: 'https://images.pokemontcg.io/swsh7/211_hires.png',
    grade: 'PSA 9',
    price: 195,
    change: 0.8,
    trend: 'down',
    score: 68,
    breakdown: { growth: 64, liquidity: 65, volatility: 60, demand: 76 },
    verdict: 'Steady accumulation candidate. Leafeon VMAX Alt Art PSA 9 trades at a significant discount to PSA 10 copies, offering collectors an accessible entry point into the Evolving Skies Alt Art tier. Minor recent softness does not indicate structural weakness.',
    verdictShort: 'Accessible entry into Evolving Skies Alt Arts.',
    rarity: 'Alt Art Ultra Rare', year: '2021', emoji: '',
    tags: ['Alt Art Ultra Rare', 'Pokémon VMAX', 'Evolving Skies', 'Secret Rare'],
    history: [
      { month: 'May', price: 148 }, { month: 'Jun', price: 155 }, { month: 'Jul', price: 160 },
      { month: 'Aug', price: 156 }, { month: 'Sep', price: 162 }, { month: 'Oct', price: 168 },
      { month: 'Nov', price: 175 }, { month: 'Dec', price: 180 }, { month: 'Jan', price: 185 },
      { month: 'Feb', price: 192 }, { month: 'Mar', price: 197 }, { month: 'Apr', price: 195 },
    ],
    sales: [
      { date: 'Apr 11', price: 196, platform: 'eBay' }, { date: 'Apr 6', price: 192, platform: 'eBay' },
      { date: 'Mar 31', price: 198, platform: 'eBay' }, { date: 'Mar 24', price: 194, platform: 'eBay' },
      { date: 'Mar 16', price: 188, platform: 'eBay' },
    ],
    marketAvg: 210,
    priceRange90d: { min: 172, max: 228 },
    volatilityPct: 13,
    volatilityLabel: 'Stable',
    liquidityScore: 65,
    liquidityLabel: 'Moderate',
    liquidityDesc: 'Consistent but moderate sales activity. Leafeon VMAX Alt Art PSA 9 attracts a steady stream of Eeveelution and Evolving Skies collectors. Sell-through time is 5–10 days at market price.',
    trendPct: 9.8,
    trendLabel: 'Steady',
    holdScore: 68,
    holdVerdict: 'HOLD',
    holdDescription: 'Leafeon VMAX Alt Art PSA 9 is a solid entry-level hold for collectors building an Evolving Skies Alt Art position. The lower price point relative to PSA 10 copies and the strong set fundamentals provide a reasonable appreciation outlook.',
    monthlyGrowth: 1.2,
    projections: {
      m3: { price: 216, pct: 11 },
      m6: { price: 238, pct: 22 },
      m12: { price: 276, pct: 42 },
    },
    holdFactors: [
      { title: 'PSA 9 Entry Point', description: 'PSA 9 copies offer a lower-cost entry into the Evolving Skies Alt Art tier with the same artwork upside. Historically the PSA 9–10 price gap widens as PSA 10 demand grows.' },
      { title: 'Eeveelution Set Collector Demand', description: 'Leafeon benefits from systematic Eeveelution collection building. Collectors who hold Umbreon and Espeon VMAX Alt Arts frequently add Leafeon to complete their sets.' },
      { title: 'Stable Floor', description: 'Low volatility and consistent sales suggest a firm price floor. The card does not appear susceptible to sharp downside corrections.' },
    ],
    aiInsights: [
      'Exact sold prices: $188–$198 AUD in the last 30 days. Minor softness over March is consistent with broad market consolidation.',
      'PSA 9 copies of Evolving Skies Alt Arts are increasingly sought as PSA 10s become less accessible at lower price points.',
      'Leafeon VMAX Alt Art PSA 10 trading at approximately $310 AUD — a ~59% premium. PSA 9 represents strong relative value.',
      'Data quality: Strong. 5 sold listings in 30-day window providing reliable market pricing signal.',
    ],
    ebayListings: [
      { title: 'Leafeon VMAX Alt Art 211/203 Evolving Skies PSA 9 MINT', date: 'Apr 11, 2026', price: 196 },
      { title: 'Pokemon Leafeon VMAX Alt Art PSA 9 Evolving Skies', date: 'Apr 6, 2026', price: 192 },
      { title: 'Leafeon VMAX 211/203 Alt Art PSA 9 — Near Mint', date: 'Mar 31, 2026', price: 198, badge: 'HIGH' },
      { title: 'Evolving Skies Leafeon VMAX Alt Art PSA 9 Mint', date: 'Mar 24, 2026', price: 194 },
      { title: 'Leafeon VMAX Alt Art PSA 9 Evolving Skies 211/203', date: 'Mar 16, 2026', price: 188, badge: 'LOW' },
    ],
  },
]

export const getCard = (id: string) => cards.find(c => c.id === id)

export const rising = [
  { id: 'eevee-promo-psa10', name: 'Eevee Black Star Promo', grade: 'PSA 10', change: 24.8, score: 79 },
  { id: 'charizard-base-psa9', name: 'Charizard Base Set', grade: 'PSA 9', change: 12.4, score: 87 },
  { id: 'umbreon-vmax-alt-psa10', name: 'Umbreon VMAX Alt Art', grade: 'PSA 10', change: 5.1, score: 95 },
  { id: 'charizard-base-psa9', name: 'Mewtwo Base Set', grade: 'PSA 10', change: 9.3, score: 81 },
  { id: 'charizard-base-psa9', name: 'Blastoise Base Set', grade: 'PSA 9', change: 7.6, score: 74 },
]

export const declining = [
  { id: 'lugia-v-alt-psa10', name: 'Lugia V Alt Art', grade: 'PSA 10', change: -8.2, score: 71 },
  { id: 'lugia-v-alt-psa10', name: 'Charizard VMAX Rainbow', grade: 'PSA 10', change: -11.4, score: 63 },
  { id: 'lugia-v-alt-psa10', name: 'Rayquaza Gold Star', grade: 'PSA 9', change: -6.8, score: 68 },
  { id: 'lugia-v-alt-psa10', name: 'Gengar Holo 1st Ed', grade: 'PSA 10', change: -4.2, score: 77 },
  { id: 'lugia-v-alt-psa10', name: 'Espeon VMAX Alt Art', grade: 'PSA 10', change: -3.1, score: 72 },
]

export const traded = [
  { id: 'charizard-base-psa9', name: 'Charizard Base Set', grade: 'PSA 9', volume: 284, score: 87 },
  { id: 'lugia-v-alt-psa10', name: 'Lugia V Alt Art', grade: 'PSA 10', volume: 211, score: 71 },
  { id: 'umbreon-vmax-alt-psa10', name: 'Umbreon VMAX Alt Art', grade: 'PSA 10', volume: 198, score: 95 },
  { id: 'eevee-promo-psa10', name: 'Eevee Black Star Promo', grade: 'PSA 10', volume: 97, score: 79 },
  { id: 'lugia-v-alt-psa10', name: 'Charizard VMAX Rainbow', grade: 'PSA 10', volume: 74, score: 63 },
]

export const ticker = [
  { name: 'Charizard PSA 9', price: 4850, change: 12.4 },
  { name: 'Lugia V Alt PSA 10', price: 1740, change: -8.2 },
  { name: 'Umbreon VMAX Alt Art PSA 10', price: 2850, change: 5.1 },
  { name: 'Eevee Promo PSA 10', price: 680, change: 24.8 },
  { name: 'Umbreon VMAX PSA 10', price: 2100, change: -11.4 },
  { name: 'Mewtwo Base PSA 10', price: 3200, change: 9.3 },
  { name: 'Blastoise Base PSA 9', price: 1850, change: 7.6 },
  { name: 'Rayquaza Gold Star PSA 10', price: 4200, change: -4.2 },
  { name: 'Gengar 1st Ed PSA 10', price: 8900, change: -3.1 },
]

export const fmt = (n: number): string => {
  if (n >= 1000000) return '$' + (n / 1000000).toFixed(1) + 'M'
  if (n >= 1000) return '$' + n.toLocaleString()
  return '$' + n
}

export const scoreColor = (s: number): string =>
  s >= 80 ? '#3de88a' : s >= 60 ? '#e8c547' : '#e8524a'

export const scoreLabel = (s: number): string =>
  s >= 80 ? 'Strong' : s >= 60 ? 'Moderate' : 'Weak'
